#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems and Deep Learning in Python                                     #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /config.yml                                                                         #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/recsys-deep-learning                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Sunday January 29th 2023 09:13:15 am                                                #
# Modified   : Tuesday February 28th 2023 01:45:01 pm                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
logging:
  version: 1
  formatters:
    console:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
      datefmt: "%m/%d/%Y %I:%M:%S %p"
    file:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s] : %(message)s"
      datefmt: "%m/%d/%Y %I:%M:%S %p"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "console"
      stream: "ext://sys.stderr"
    file:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: file
      when: midnight
      interval: 1
      backupCount: 0
      level: "DEBUG"
      filename: logs/recsys.log
  root:
    level: "DEBUG"
    handlers: ["console", "file"]
  disable_existing_loggers: False


workspace: ${WORKSPACE}
workspaces:
  presidio:
    name: presidio
    description: Production Workspace
    data:
      dataset: devstudio/presidio/dataset.db
      experiment: devstudio/presidio/experiment.db
      model: devstudio/presidio/model.db
      datasize: 1.0
    cache:
      location: devstudio/presidio/cache.db
      ttl: 7
      max_size: 512
      enabled: True
  enrico:
    name: enrico
    description: Development Workspace
    data:
      dataset: devstudio/enrico/dataset.db
      experiment: devstudio/enrico/experiment.db
      model: devstudio/enrico/model.db
      datasize: 0.2
    cache:
      location: devstudio/enrico/cache.db
      ttl: 7
      max_size: 512
      enabled: True
  backflip:
    name: backflip
    description: Rapid Development Workspace
    data:
      dataset: devstudio/backflip/dataset.db
      experiment: devstudio/backflip/experiment.db
      model: devstudio/backflip/model.db
      datasize: .05
    cache:
      location: devstudio/backflip/cache.db
      ttl: 7
      max_size: 512
      enabled: True

idgen:
  database: devstudio/idgen.db