#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems in Python 1: Neighborhood Methods                               #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /recsys/etl/MLproject                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Recsys-1-Neighborhood                              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday March 4th 2023 11:24:45 am                                                 #
# Modified   : Saturday March 4th 2023 06:17:33 pm                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
name: etl

conda_env: environment.yml

entry_points: # noqa F899
  extract:
    parameters:
      source: {type: string, default: "https://files.grouplens.org/datasets/movielens/ml-25m.zip"}
      destination: {type: path, default: "../../data/ext"}
      raw_dir: {type: path, default: "../../data/raw"}
      member: {type: str, default: "ratings.csv"}
    command: "python extract.py --source {source} --destination {destination} --raw_dir {raw_dir} -- member {member}"

  transform:
    parameters:
      source: {type: path, default: "../../data/raw/ratings.csv"}
      destination: {type: path, default: "../../data/raw/ratings.pkl"}
    command: "python  transform.py --source {source} --destination {destination}"

  load:
    parameters:
      source: {type: path, default: "../../data/prod/train.pkl"}
      destination: {type: path, default: "../../data/dev/"}
      sample_size: {type: float, default: 0.1}
      train_size: {type: float, default: 0.8}
      train_filename: {type: string, default: "train.pkl"}
      test_filename: {type: string, default: "test.pkl"}
    command: "python load.py --source {source} --destination {destination} --sample_size {sample_size} --train_size {train_size} -- train_filename {train_filename}, --test_filename {test_filename}"

  etl:
    command: "python etl.py"