#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems in Python 1: Neighborhood Methods                               #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /config/etl.yml                                                                     #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/recsys-01-collaborative-filtering                  #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday February 20th 2023 07:09:58 am                                               #
# Modified   : Thursday March 9th 2023 04:24:34 pm                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
pipeline:
  name: movielens25m_etl
  description: Extracts, transforms and loads the GroupLens Movielens25M ratings dataset
  tasks:
    # -------------------------------------------------------------------------------------------- #
    #                                     MOVIELENS25M                                             #
    # -------------------------------------------------------------------------------------------- #

    - name: source_movielens25m
      description: Obtain Movielens25M Dataset from the Grouplens website
      operator:
        name: ZipDownloader
        module: recsys.operator.io.remote
        params:
          source: https://files.grouplens.org/datasets/movielens/ml-25m.zip
          destination: data/ext/ml-25m.zip
          force: False

    - name: extract_ratings
      description: Extract ratings file into raw directory.
      operator:
        name: ZipExtractor
        module: recsys.operator.io.compress
        params:
          source: data/ext/ml-25m.zip
          destination: data/raw/
          member: ratings.csv
          force: False

    - name: split_dataset
      description: Split file into training and test set
      operator:
        name: TemporalTrainTestSplit
        module: recsys.operator.data.split
        params:
          source: data/raw/ratings.csv
          train_filepath: data/split/train.pkl
          test_filepath: data/split/test.pkl
          train_size: 0.8
          timestamp_var: timestamp
          force: False

    - name: subsample_dataset
      description: Create a subsample of the dataset for development purposes
      operator:
        name: RandomTemporalInteractionThresholdSampling
        module: recsys.operator.data.sampling
        params:
          source: data/split/train.pkl
          destination: data/clean/ratings.pkl
          umax: 1000
          imax: 1000
          frac: 0.1
          force: False

    - name: split_dev_set
      description: Split development set into train and test sets
      operator:
        name: TemporalTrainTestSplit
        module: recsys.operator.data.split
        params:
          source: data/clean/ratings.pkl
          train_filepath: data/clean/train.pkl
          test_filepath: data/clean/test.pkl
          train_size: 0.8
          timestamp_var: timestamp
          force: False