#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems and Deep Learning in Python                                     #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /config/etl.yml                                                                     #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/recsys-deep-learning                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday February 20th 2023 07:09:58 am                                               #
# Modified   : Tuesday February 21st 2023 11:46:13 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
pipeline:
  name: movielens25m_etl
  description: Extracts, transforms and loads the GroupLens Movielens25M ratings dataset
  tasks:
    # -------------------------------------------------------------------------------------------- #
    #                                     REGISTER DATA SOURCE                                     #
    # -------------------------------------------------------------------------------------------- #
    1:
      task:
        name: create_movielens25m_datasource
        description: Create Movielens25M Datasource
      input:
        type: uri
        uri: https://files.grouplens.org/datasets/movielens/ml-25m.zip
      operator:
        name: DatasourceFactory
        module: recsys.data.source
      output:
        type: Datasource
        name: movielens25m
        title: MovieLens 25M Dataset
        description: This dataset (ml-25m) describes 5-star rating and free-text tagging activity from MovieLens, a movie recommendation service. It contains 25000095 ratings and 1093360 tag applications across 62423 movies. These data were created by 162541 users between January 09, 1995 and November 21, 2019. This dataset was generated on November 21, 2019.
        author: Jesse Vig, Shilad Sen, and John Riedl
        publisher: GroupLens Research
        version: N/A
        generated: November 21, 2019.
        website: https://grouplens.org/datasets/movielens/25m/
        uri: https://files.grouplens.org/datasets/movielens/ml-25m.zip
        doi: https://doi.org/10.1145/2827872
        email: grouplens-info@umn.edu
        filepath: data/movielens25m/ext/
        note: N/A
      force: False

    # -------------------------------------------------------------------------------------------- #
    2:
      task:
        name: create_spotify_playlist_datasource
        description: Create Spotify Million Playlist Datasource
      input:
        type: uri
        uri: https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files?unique_download_uri=204054&challenge_id=277
      operator:
        name: DatasourceFactory
        module: recsys.data.source
      output:
        type: Datasource
        name: spotify
        title: Spotify Million Playlist Dataset
        description: Sampled from the over 4 billion public playlists on Spotify, this dataset of 1 million playlists consist of over 2 million unique tracks by nearly 300,000 artists, and represents the largest public dataset of music playlists in the world. The dataset includes public playlists created by US Spotify users between January 2010 and November 2017.
        author: Cedric De Boom, Paul Lamere, 	Ching-Wei Chen, 	Ben Carterette, 	Christophe Charbuillet, 	Jean Garcia-Gathright, 	James Kirk, 	James McInerney, 	Vidhya Murali, 	Hugh Rawlinson, 	Sravana Reddy, 	Marc Romejin, 	Romain Yon, 	Yu Zhao,
        publisher: Spotify Research
        version: N/A
        released: September 2020
        website: https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge#summary
        uri: https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files?unique_download_uri=204056&challenge_id=277
        doi: arXiv:1810.01520v2 [cs.IR] 31 Aug 2019
        email: yoogottam@aicrowd.com
        filepath: data/spotify/ext/
        note: A smaller auxiliary version of the dataset may be obtained from https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files?unique_download_uri=204057&challenge_id=277
      force: False

    # -------------------------------------------------------------------------------------------- #
    3:
      task:
        name: create_tenrec_benchmark_datasource
        description: Create Tenrec Benchmark Datasource
      input:
        type: uri
        uri: https://static.qblv.qq.com/qblv/h5/algo-frontend/tenrec_dataset.html
      operator:
        name: DatasourceFactory
        module: recsys.data.source
      output:
        type: Datasource
        name: tenrec
        title: Tenrec - A Large-scale Multipurpose Benchmark Dataset for Recommender Systems
        description: Tenrec is a large-scale multipurpose benchmark dataset for recommender systems where data was collected from two feeds (articles and videos) recommendation platforms.
        author: Guanghu Yuan, Fajie Yuan, Yudong Li, Beibei Kong, Shujie Li, Lei Chen, Min Yang, Chenyun YU, Bo Hu, Zang Li, Yu Xu, Xiaohu Qie
        publisher:
        version: N/A
        released: 13 Oct 2022
        website: https://github.com/yuangh-x/2022-NIPS-Tenrec
        uri: https://static.qblv.qq.com/qblv/h5/algo-frontend/tenrec_dataset.html
        doi: arXiv:2210.10629 [cs.IR]
        email:
        filepath: data/trenrec/ext
        note: A smaller auxiliary version of the dataset may be obtained from https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files?unique_download_uri=204057&challenge_id=277
      force: False

    # -------------------------------------------------------------------------------------------- #
    #                                     DOWNLOAD MOVIELENS25M                                    #
    # -------------------------------------------------------------------------------------------- #
    4:
      task:
        name: download_movielens25m
        description: Download Movielens25M Datasource
      input:
        type: DataSource
        name: movielens25m
      operator:
        name: Downloader
        module: recsys.data.extract
      params:
        name: download_movielens25M
        description: Download Movielen25M from GroupLens site

        destination: data/ext/
        endpoint: data/ext/ml-25m.zip
        force: False
    # -------------------------------------------------------------------------------------------- #
    #                                      EXTRACT                                                 #
    # -------------------------------------------------------------------------------------------- #
    2:
      operator: ZipExtractor
      module: recsys.data.extract
      params:
        name: extract_ratings_data
        description: Extract ratings data from zip archive
        source: data/ext/ml-25m.zip
        member: ml-25m/ratings.csv
        destination: data/ext/
        endpoint: data/ext/ml-25m/ratings.csv
        force: False

    # -------------------------------------------------------------------------------------------- #
    #                                     CREATE DATASET                                           #
    # -------------------------------------------------------------------------------------------- #
    3:
      operator: DatasetFactory
      module: recsys.entity.rating
      params:
        name: subsample_movielens25m
        description: Subsamples Movielens25M Dataset
        source: data/ext/ratings.csv
        destination: data/stage/ratings.pkl
        workspace: alpha
        force: False

    # -------------------------------------------------------------------------------------------- #
    #                                    SUBSAMPLE                                                 #
    # -------------------------------------------------------------------------------------------- #
    3:
      operator: Subsample
      module: recsys.data.filter
      params:
        name: subsample_movielens25m
        description: Subsamples Movielens25M Dataset
        source: data/ext/ratings.csv
        destination: data/stage/ratings.pkl
        workspace: alpha
        force: False


