#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Recommender Systems and Deep Learning in Python                                     #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.6                                                                              #
# Filename   : /config/etl.yml                                                                     #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/recsys-deep-learning                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday February 20th 2023 07:09:58 am                                               #
# Modified   : Thursday February 23rd 2023 03:40:22 am                                             #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
pipeline:
  name: movielens25m_etl
  description: Extracts, transforms and loads the GroupLens Movielens25M ratings dataset
  tasks:
    # -------------------------------------------------------------------------------------------- #
    #                                     MOVIELENS25M                                             #
    # -------------------------------------------------------------------------------------------- #
    1:
      task:
        name: source_movielens25m
        description: Obtain Movielens25M Dataset from the Grouplens website
        stage: source
      operator:
        name: DownloadZipExtract
        module: recsys.operator.file
      params:
        source: https://files.grouplens.org/datasets/movielens/ml-25m.zip
        download: data/movielens25m/ext/
        extract: data/movielens25m/raw/
        force: False

    # -------------------------------------------------------------------------------------------- #
    #                                     SPOTIFY                                                  #
    # -------------------------------------------------------------------------------------------- #
    2:
      tasks:
        name: spotify
        description: Spotify Million Playlist Benchmark Dataset
        stage: source
      operator:
        name: DownloaderFile
        module: recsys.operator.file
      params:
        uri1: https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files?unique_download_uri=204765&challenge_id=277
        uri2: https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files?unique_download_uri=204766&challenge_id=277
        destination: data/spotify/ext/
        force: False

    # -------------------------------------------------------------------------------------------- #
    #                                    TENREC                                                    #
    # -------------------------------------------------------------------------------------------- #
    3:
      tasks:
        name: load_tenrec_dataset
        description: Obtain Tenrec, a large-scale multipurpose benchmark dataset
        stage: source
      operator:
        name: DownloaderFile
        module: recsys.operator.file
      params:
        source: https://static.qblv.qq.com/qblv/h5/algo-frontend/tenrec_dataset.html#deal
        destination: data/tenrec/ext/
        force: False